// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPbLcnmHoY6Fz6WtzhODMpORokC8giGk',
    appId: '1:862316793252:web:08b8dc03bd3c9b17ccc531',
    messagingSenderId: '862316793252',
    projectId: 'newchat-36ec2',
    authDomain: 'newchat-36ec2.firebaseapp.com',
    storageBucket: 'newchat-36ec2.firebasestorage.app',
    measurementId: 'G-BG30269J3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZUf9QCHrn_IW4LXrJDmLg1sQrVQtaLI',
    appId: '1:862316793252:android:432f1f9192eaa9bdccc531',
    messagingSenderId: '862316793252',
    projectId: 'newchat-36ec2',
    storageBucket: 'newchat-36ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG33vFwiZ0f02qG5m_f85SatFxJVLvoQE',
    appId: '1:862316793252:ios:3e889af1d547d494ccc531',
    messagingSenderId: '862316793252',
    projectId: 'newchat-36ec2',
    storageBucket: 'newchat-36ec2.firebasestorage.app',
    iosBundleId: 'com.example.newChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG33vFwiZ0f02qG5m_f85SatFxJVLvoQE',
    appId: '1:862316793252:ios:3e889af1d547d494ccc531',
    messagingSenderId: '862316793252',
    projectId: 'newchat-36ec2',
    storageBucket: 'newchat-36ec2.firebasestorage.app',
    iosBundleId: 'com.example.newChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJPbLcnmHoY6Fz6WtzhODMpORokC8giGk',
    appId: '1:862316793252:web:aa223e5a78f878b5ccc531',
    messagingSenderId: '862316793252',
    projectId: 'newchat-36ec2',
    authDomain: 'newchat-36ec2.firebaseapp.com',
    storageBucket: 'newchat-36ec2.firebasestorage.app',
    measurementId: 'G-D63X24FEWE',
  );
}
